#############################################################################
# Makefile for building: QQJson
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  QQJson.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile QQJson.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../Qt5.7.0/5.7/gcc_64/include -I../../Qt5.7.0/5.7/gcc_64/include/QtGui -I../../Qt5.7.0/5.7/gcc_64/include/QtCore -I. -I../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QQJson1.0.0
DISTDIR = /home/lee/github/QQJson/.tmp/QQJson1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/lee/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/lee/Qt5.7.0/5.7/gcc_64/lib -lQt5Gui -L/usr/lib64 -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = AbstractContext.cpp \
		AbstractState.cpp \
		ExpectArrayValue.cpp \
		ExpectColonState.cpp \
		ExpectCommaOrEndState.cpp \
		ExpectKeyState.cpp \
		ExpectValueState.cpp \
		main.cpp \
		qqjson.cpp \
		qqjson_array.cpp \
		qqjson_boolen.cpp \
		qqjson_null.cpp \
		qqjson_number.cpp \
		qqjson_object.cpp \
		QQJsonContext.cpp \
		qqjsondocument.cpp \
		qqjsonkey.cpp \
		qqjsonstring.cpp \
		qqjsonx.cpp \
		StartState.cpp 
OBJECTS       = AbstractContext.o \
		AbstractState.o \
		ExpectArrayValue.o \
		ExpectColonState.o \
		ExpectCommaOrEndState.o \
		ExpectKeyState.o \
		ExpectValueState.o \
		main.o \
		qqjson.o \
		qqjson_array.o \
		qqjson_boolen.o \
		qqjson_null.o \
		qqjson_number.o \
		qqjson_object.o \
		QQJsonContext.o \
		qqjsondocument.o \
		qqjsonkey.o \
		qqjsonstring.o \
		qqjsonx.o \
		StartState.o
DIST          = ../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		QQJson.pro AbstractContext.h \
		AbstractState.h \
		ExpectArrayValue.h \
		ExpectColonState.h \
		ExpectCommaOrEndState.h \
		ExpectKeyState.h \
		ExpectValueState.h \
		qqjson.h \
		qqjson_array.h \
		qqjson_boolen.h \
		qqjson_null.h \
		qqjson_number.h \
		qqjson_object.h \
		QQJsonContext.h \
		qqjsondocument.h \
		qqjsonkey.h \
		qqjsonstring.h \
		qqjsonx.h \
		StartState.h AbstractContext.cpp \
		AbstractState.cpp \
		ExpectArrayValue.cpp \
		ExpectColonState.cpp \
		ExpectCommaOrEndState.cpp \
		ExpectKeyState.cpp \
		ExpectValueState.cpp \
		main.cpp \
		qqjson.cpp \
		qqjson_array.cpp \
		qqjson_boolen.cpp \
		qqjson_null.cpp \
		qqjson_number.cpp \
		qqjson_object.cpp \
		QQJsonContext.cpp \
		qqjsondocument.cpp \
		qqjsonkey.cpp \
		qqjsonstring.cpp \
		qqjsonx.cpp \
		StartState.cpp
QMAKE_TARGET  = QQJson
DESTDIR       = 
TARGET        = QQJson


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QQJson.pro ../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		QQJson.pro \
		../../Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl \
		../../Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile QQJson.pro
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
QQJson.pro:
../../Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl:
../../Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QQJson.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents AbstractContext.h AbstractState.h ExpectArrayValue.h ExpectColonState.h ExpectCommaOrEndState.h ExpectKeyState.h ExpectValueState.h qqjson.h qqjson_array.h qqjson_boolen.h qqjson_null.h qqjson_number.h qqjson_object.h QQJsonContext.h qqjsondocument.h qqjsonkey.h qqjsonstring.h qqjsonx.h StartState.h $(DISTDIR)/
	$(COPY_FILE) --parents AbstractContext.cpp AbstractState.cpp ExpectArrayValue.cpp ExpectColonState.cpp ExpectCommaOrEndState.cpp ExpectKeyState.cpp ExpectValueState.cpp main.cpp qqjson.cpp qqjson_array.cpp qqjson_boolen.cpp qqjson_null.cpp qqjson_number.cpp qqjson_object.cpp QQJsonContext.cpp qqjsondocument.cpp qqjsonkey.cpp qqjsonstring.cpp qqjsonx.cpp StartState.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

AbstractContext.o: AbstractContext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractContext.o AbstractContext.cpp

AbstractState.o: AbstractState.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractState.o AbstractState.cpp

ExpectArrayValue.o: ExpectArrayValue.cpp ExpectArrayValue.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h \
		qqjson_number.h \
		ExpectCommaOrEndState.h \
		ExpectValueState.h \
		qqjson_boolen.h \
		qqjson_null.h \
		qqjsonstring.h \
		qqjson_array.h \
		qqjson_object.h \
		ExpectKeyState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExpectArrayValue.o ExpectArrayValue.cpp

ExpectColonState.o: ExpectColonState.cpp ExpectColonState.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExpectColonState.o ExpectColonState.cpp

ExpectCommaOrEndState.o: ExpectCommaOrEndState.cpp ExpectCommaOrEndState.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h \
		ExpectArrayValue.h \
		ExpectKeyState.h \
		ExpectValueState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExpectCommaOrEndState.o ExpectCommaOrEndState.cpp

ExpectKeyState.o: ExpectKeyState.cpp ExpectKeyState.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h \
		qqjsonkey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExpectKeyState.o ExpectKeyState.cpp

ExpectValueState.o: ExpectValueState.cpp ExpectValueState.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h \
		qqjson_number.h \
		qqjson_object.h \
		qqjson_null.h \
		qqjsonstring.h \
		qqjson_boolen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExpectValueState.o ExpectValueState.cpp

main.o: main.cpp qqjsondocument.h \
		qqjsonx.h \
		qqjsonkey.h \
		qqjson_object.h \
		qqjsonstring.h \
		qqjson_array.h \
		qqjson_null.h \
		qqjson_number.h \
		qqjson_boolen.h \
		QQJsonContext.h \
		AbstractContext.h \
		AbstractState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qqjson.o: qqjson.cpp qqjson.h \
		qqjsondocument.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson.o qqjson.cpp

qqjson_array.o: qqjson_array.cpp qqjson_array.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson_array.o qqjson_array.cpp

qqjson_boolen.o: qqjson_boolen.cpp qqjson_boolen.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson_boolen.o qqjson_boolen.cpp

qqjson_null.o: qqjson_null.cpp qqjson_null.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson_null.o qqjson_null.cpp

qqjson_number.o: qqjson_number.cpp qqjson_number.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson_number.o qqjson_number.cpp

qqjson_object.o: qqjson_object.cpp qqjson_object.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjson_object.o qqjson_object.cpp

QQJsonContext.o: QQJsonContext.cpp QQJsonContext.h \
		AbstractContext.h \
		qqjsonx.h \
		AbstractState.h \
		qqjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QQJsonContext.o QQJsonContext.cpp

qqjsondocument.o: qqjsondocument.cpp qqjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjsondocument.o qqjsondocument.cpp

qqjsonkey.o: qqjsonkey.cpp qqjsonkey.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjsonkey.o qqjsonkey.cpp

qqjsonstring.o: qqjsonstring.cpp qqjsonstring.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjsonstring.o qqjsonstring.cpp

qqjsonx.o: qqjsonx.cpp qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqjsonx.o qqjsonx.cpp

StartState.o: StartState.cpp StartState.h \
		AbstractState.h \
		qqjsondocument.h \
		AbstractContext.h \
		qqjsonx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StartState.o StartState.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

